# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('comments', models.CharField(default='', max_length=100)),
                ('expiration', models.DateTimeField(default='')),
            ],
            options={
                'ordering': ('expiration',),
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('desription', models.CharField(default='', max_length=1000)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
