# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sample Item', max_length=100)),
                ('comments', models.CharField(default='', max_length=1000)),
                ('expiration', models.DateField(default='')),
                ('amount', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ('expiration',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Store', max_length=100)),
                ('description', models.CharField(default='N/A', max_length=1000)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.Store'),
        ),
    ]
