# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
