# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20160319_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expired',
        ),
    ]
