# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20160316_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='desription',
            new_name='description',
        ),
    ]
