# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_item_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
    ]
